[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'No build step required'"]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "3000"
